openapi: 3.0.0
version: 1
datastore:
  filename: data.json
scheduler:
  period_sec: 5
eventstore:
  url: http://localhost:8090
database:
  url: mysql+pymysql://user:password@acit3855group45kafka.eastus2.cloudapp.azure.com:3306/events