openapi: 3.0.0
version: 1
datastore:
  user: user
  password: password
  hostname: acit3855group45kafka.eastus2.cloudapp.azure.com
  port: 3306
  db: events
scheduler:
  period_sec: 5
eventstore:
  url: http://localhost:8090
events:
  hostname: acit3855group45kafka.eastus2.cloudapp.azure.com
  port: 9092
  topic: events 
kafka:
  max_retries: 5
  retry_sleep: 10